### ISSUE TITLE
NPU usage is always keeps at 0% when running hello_world test

### ISSUE THREAD

**Issue by mattchai** [amd/ryzen-ai-documentation#299] opened 2024-08-10 14:20 UTC
Hello_world.py file will run CPU and NPU inference, but I found NPU usage always keeps at 0% during running, could you please help to explain why NPU usage is always keeps at 0%.

**Comment by uday610** [comment] 2024-08-21 15:22
This issue is duplicate of issue reported in Ryzen AI SW repo, hence closing

**Closed by uday610** 2024-08-21 15:22 UTC
